// GENERATED by scripts/gen-client-roster.mjs — do not edit.
// Source of truth: packages/bundle/ui/client.yml (the UI bundle's roster).
//
// The page composes from data like the host does, but a browser bundle needs static
// imports, so the roster is generated here and `pnpm run build:web` regenerates it.
// `pnpm test` fails when this file is stale.

import type { Plugin } from '@deepseek-ai/cordis'
import * as plugin0 from '@mediabase/connection'
import * as plugin1 from '@mediabase/i18n'
import * as plugin2 from '@mediabase/ui'
import * as plugin3 from '@mediabase/ui-web'

/** A client plugin module, as the roster names it. */
export type ClientPlugin = Plugin.Object

/** The browser roster in MOUNT ORDER: registries first, the shell last. */
export const CLIENT_ROSTER: ReadonlyArray<{ id: string; name: string; plugin: ClientPlugin }> = [
  { id: 'connection', name: '@mediabase/connection', plugin: plugin0 as ClientPlugin },
  { id: 'i18n', name: '@mediabase/i18n', plugin: plugin1 as ClientPlugin },
  { id: 'ui', name: '@mediabase/ui', plugin: plugin2 as ClientPlugin },
  { id: 'shell', name: '@mediabase/ui-web', plugin: plugin3 as ClientPlugin },
]
